const rcrdOrFldNameSnctncCase = {
      GRFUser: "Author",
      weekMealPlan: "Week Meal Plan",
      day: "Day",
      meal: "Meal",
      genRecipe: "Recipe",
      mealIngredient: "Meal Ingredient",
      genRecipeIngredient: "Recipe Ingredient",
      ingredient: "Base Ingredient",
      unitOfMeasure: "UOM",
      weightType: "Weight Type",
      brand: "Brand",
      name: "Name",
      qty: "Qty",
      defaultQty: "Default Qty",
      photoURL: "Photo URL",
      dayOfWeek: "Day of Week",
      mealType: "Meal Type",
      defaultMealType: "Meal Type",
      defaultPrepInstructions: "Prep Instructions",
      calories: "Calories",
      carbs: "Carbs",
      protein: "Protein",
      fat: "Fat",
      fiber: "Fiber",
      createdAt: "Date Created",
      updatedAt: "Last Update",
    };
export default rcrdOrFldNameSnctncCase;